config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  root 'quotes#index'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quotes = Quote.all
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.create(body: params[:quote][:body])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quotes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quotes/_form.html.erb
<%= form_for @quote, remote: true do |f| %>
  <%= f.text_field :body %>
  <%= f.submit %>
<% end %>

app/views/quotes/_quote.html.erb
<li><%= quote.body %></li>

app/views/quotes/create.js.erb
// $("#quote-list").html("<%= j(render @quotes) %>");
// $("#quote_body").val("");

$("#quote-list").append("<%= j(render @quote) %>");
$("#quote_body").val("");

app/views/quotes/index.html.erb
<h1>These are a few of my favorite things</h1>

<ul id="quote-list">
  <%= render @quotes %>
</ul>

<p><%= link_to "New Quote", new_quote_path, remote: true %></p>

<div id="quote-form"></div>

app/views/quotes/new.js.erb
$("#quote-form").html("<%= escape_javascript(render 'form') %>");